### ISSUE TITLE
Number of boundary matches in Stargazers data set?

### ISSUE THREAD

**Issue by rybesh** [cfournie/segmentation.evaluation#1]
I am working with the code in the `preview_b` branch of your repo, which you so kindly provided for me earlier this spring. I am trying to use it to replicate the numbers in your thesis at http://hdl.handle.net/10393/24064, and I am having a little trouble.

Specifically I am trying to replicate the numbers in Table 5.3b on page 154 of your thesis. See the following test code: https://gist.github.com/rybesh/5627500

This code is using  `linear_edit_distance` from the `preview_b` branch of your repo: https://github.com/cfournie/segmentation.evaluation/blob/preview_b/src/python/main/segeval/similarity/distance/SingleBoundaryDistance.py#L36

The test code shows 72 additions/deletions and 28 transpositions, but **211** matches rather than 125.

Looking at the routine for calculating matches I see: 

``` python
matches = 0
for string_a_i, string_b_i in zip(string_a, string_b):
    matches += len(set(string_a_i).union(set(string_b_i)))
```

https://github.com/cfournie/segmentation.evaluation/blob/preview_b/src/python/main/segeval/similarity/distance/MultipleBoundaryDistance.py#L289-291

I couldn't convince myself that this was correct, so I replaced that code with:

``` python
bnds_per_pb = [ sum(chain(*pair)) for pair in zip(string_a, string_b) ]
assert all((x <= 2) for x in bnds_per_pb)
matches = len([ x for x in bnds_per_pb if x == 2 ])
```

(Note that I am working only with single-boundary-type segmentations.)

But, this gives me yet a third figure for the number of matches: **83**.

So, now I am a bit confused as to how the number of matches is being or should be counted in order to calculate the B variant of boundary similarity. Since I am hoping to use the approach outlined in your thesis for a segmentation evaluation I am conducting, any help you could provide would be much appreciated.

**Comment by cfournie** [comment]
In v1.0 to v1.1 of SegEval, and the paper titled 'Segmentation Similarity and Agreement', the edit distance used will model transposition edits as reversals, where a set of boundaries (perhaps more than two from each segmentation) is reversed and if it matches the set of boundaries present then it is recorded as a transposition containing X number of boundaries (and whose penalty is scaled in relation to the contained boundaries, e.g., a segmentation _A_ represented as a sequence of boundary sets `[(1), (1), (), ()]` that is compared against a segmentation _B_ `[(), (), (1), (1)]` could have _A_ reversed to appear identical to B (`[(), (), (1), (1)]`).  This would be a single transposition of 2 boundaries.

The edit distance in v2.0, my thesis, and the paper titled 'Evaluating Text Segmentation using Boundary Edit Distance', models a transposition as being between only one boundary in segmentation _A_ and one in _B_, e.g., the previous example would produce two transpositions each concerning only one pair of boundaries each.  That is why there is a discrepancy in the number of edits (but not, in most cases, in the final weighted similarity produced by version v1.0 and v1.1 which would adjust the severity of a transposition by the number of boundaries contained in a reversal).

The release of v2.0+ corrects this discrepancy.
